# Generated by Django 4.2 on 2023-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_description_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ПОДУШКА', 'Подушки'), ('МАТРАС', 'Матрасы')], default='', max_length=255),
        ),
    ]
